#!/bin/zsh

CLOCK='date +"%a, %e %B | %T"'

while true
do
  if [ "$(head -n 1 /sys/class/power_supply/BAT1/status | xargs echo -n)" != "Discharging" ]
  then
    BAT_CHAR="▱"
    NONBAT_CHAR="▰"
  else
    BAT_CHAR="▰"
    NONBAT_CHAR="▱"
  fi
  BAT_STATUS=$(cat /sys/class/power_supply/BAT1/status)
  if [ "${BAT_STATUS}" != "Discharging" ]
  then
    BAT_SYMBOL="C"
  else
    BAT_SYMBOL="D"
  fi
  BAT_PERC=$(cat /sys/class/power_supply/BAT1/capacity)
  BAT_BARS=$(( ${BAT_PERC} / 10 ))
  NONBAT_BARS=$(( 10 - $BAT_BARS ))
  PRINT_BAT_BARS=$(printf "${BAT_CHAR}%.0s" {1..${BAT_BARS}})
  if [ "${NONBAT_BARS}" != "0" ]
  then
    PRINT_NONBAT_BARS=$(printf "${NONBAT_CHAR}%.0s" {1..${NONBAT_BARS}})
  else
    PRINT_NONBAT_BARS=""
  fi
  BATTERY="<${BAT_SYMBOL}> ${PRINT_BAT_BARS}${PRINT_NONBAT_BARS} ${BAT_PERC}%"

  MUSIC=$(mpc current)
  if [ -n "$MUSIC" ]; then
    MUSIC="[$MUSIC]  "
  fi

  xsetroot -name "${MUSIC}[$BATTERY]  [`eval $CLOCK`]"
  sleep 1
done


